"""init

Revision ID: 089551a8f7e3
Revises: 
Create Date: 2025-10-04 21:44:02.234669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089551a8f7e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_uuid", sa.String(), nullable=False),
        sa.Column("uuid_key", sa.String(), nullable=False),
        sa.Column(
            "destination",
            sa.Enum("email", "sms", "telegram", name="notificationdestination"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("success", "in_progress", "failure", name="notificationstatus"),
            nullable=False,
        ),
        sa.Column(
            "routing_key",
            sa.Enum(
                "auth.send_code",
                "auth.reset_password",
                "bid.new_bid_placed",
                "bid.you_won_bid",
                "bid.you_lost_bid",
                "order.status_updated",
                name="notificationroutingkey",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
