"""init

Revision ID: 69d889ac0a1b
Revises: 
Create Date: 2025-08-11 11:48:03.569683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69d889ac0a1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('uuid_key', sa.String(), nullable=False),
    sa.Column('destination', sa.Enum('EMAIL', 'SMS', name='notificationdestination'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'IN_PROGRESS', 'FAILURE', name='notificationstatus'), nullable=False),
    sa.Column('routing_key', sa.Enum('AUTH_SEND_CODE', name='notificationpurpose'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
