"""init

Revision ID: 7a1b7d857510
Revises: 
Create Date: 2025-12-16 10:55:56.701088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a1b7d857510'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(), nullable=False),
    sa.Column('uuid_key', sa.String(), nullable=False),
    sa.Column('destination', sa.Enum('EMAIL', 'SMS', 'TELEGRAM', name='notificationdestination'), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'IN_PROGRESS', 'FAILURE', name='notificationstatus'), nullable=False),
    sa.Column('routing_key', sa.Enum('AUTH_SEND_CODE', 'AUTH_RESET_PASSWORD', 'NEW_BID_PLACED', 'YOU_WON_BID', 'YOU_LOST_BID', 'ORDER_STATUS_UPDATED', name='notificationroutingkey'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification')
    # ### end Alembic commands ###
