"""fix notification

Revision ID: b0544d7811de
Revises: 69d889ac0a1b
Create Date: 2025-10-04 21:39:27.540891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0544d7811de'
down_revision: Union[str, Sequence[str], None] = '69d889ac0a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'routing_key',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.Enum('AUTH_SEND_CODE', 'AUTH_RESET_PASSWORD', name='notificationroutingkey'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'routing_key',
               existing_type=sa.Enum('AUTH_SEND_CODE', 'AUTH_RESET_PASSWORD', name='notificationroutingkey'),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)
    # ### end Alembic commands ###
