"""add new destination

Revision ID: b7a422a4230a
Revises: 089551a8f7e3
Create Date: 2025-12-15 11:46:09.311857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7a422a4230a'
down_revision: Union[str, Sequence[str], None] = '089551a8f7e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'destination',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Enum('EMAIL', 'SMS', 'TELEGRAM', name='notificationdestination'),
               existing_nullable=False)
    op.alter_column('notification', 'routing_key',
               existing_type=sa.VARCHAR(length=19),
               type_=sa.Enum('AUTH_SEND_CODE', 'AUTH_RESET_PASSWORD', 'NEW_BID_PLACED', 'YOU_WON_BID', 'YOU_LOST_BID', 'ORDER_STATUS_UPDATED', name='notificationroutingkey'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'routing_key',
               existing_type=sa.Enum('AUTH_SEND_CODE', 'AUTH_RESET_PASSWORD', 'NEW_BID_PLACED', 'YOU_WON_BID', 'YOU_LOST_BID', 'ORDER_STATUS_UPDATED', name='notificationroutingkey'),
               type_=sa.VARCHAR(length=19),
               existing_nullable=False)
    op.alter_column('notification', 'destination',
               existing_type=sa.Enum('EMAIL', 'SMS', 'TELEGRAM', name='notificationdestination'),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)
    # ### end Alembic commands ###
